version: '3.8'

services:
  cache:
    image: redis:6.2-alpine
    container_name: shequ-cache
    restart: always
    expose:
      - 6379
    volumes:
      - shequ-cache:/data
    command: redis-server --save 20 1 --loglevel warning

  node:
    image: node:16
    container_name: shequ
    restart: always
    working_dir: /home/ubuntu/shequ
    depends_on:
      - shequ-cache
    environment:
      REDIS_HOST: shequ-cache
      REDIS_PORT: 6379
    volumes:
      - ./:/home/ubuntu/shequ
    links:
      - shequ-cache
    command: bash -c "npm config set cache /tmp --global && npm i --production=false && npm run build && node dist/index.js"
