version: '3.1'

services:
  node:
    image: node:16

    container_name: shequ
    working_dir: /home/ubuntu/shequ

    volumes:
      - ./:/home/ubuntu/shequ

    command: >
      bash -c "
        npm config set cache /tmp --global 
        && npm i 
        && npm run build
        && node dist/index.js
      "
