version: '3.1'

services:
  cache:
    image: redis:latest
    restart: always

    container_name: shequ-cache

    ports:
      - 10001:6379

    command: redis-server --save 20 1 --loglevel warning

  node:
    image: node:16

    depends_on:
      - cache

    container_name: shequ
    working_dir: /home/ubuntu/shequ

    environment:
      REDIS_HOST: cache
      REDIS_PORT: 10001

    volumes:
      - ./:/home/ubuntu/shequ

    links:
      - cache

    command: bash -c "npm config set cache /tmp --global && npm i --production=false && npm run build && node dist/index.js"
